markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: thangdnsf
author: "Thangdn"
email: thangdn.tlu@gmail.com
name: "Thangdn"
url: http://thangdn.com
domain: thangdn.com
all_categories: [
["Courses", "Courses","/posts/Courses.html",[["Mathematics course", "Mathematics","/posts/Mathematiccourse.html"],
                                            ["Machine Learning course", "Machine Learning","/posts/Machinelearningcourse.html"], 
                                            ["Deep Learning course", "Deep Learning","/posts/Deeplearningcourse.html"]]], 
["Blog", "Blog","/posts/blog.html",[["Mathematics", "Mathematics","/posts/Mathematic.html"],
                                    ["Machine Learning", "Machine Learning","/posts/Machinelearning.html"],
                                    ["Deep Learning", "Deep Learning","/posts/Deeplearning.html"]]],
["Project", "Project","/posts/Project.html",[]], 
["other", "Other","/posts/other.html",[]],
["about", "About","/about.html",[]],
["Github", "Github","https://github.com/thangdnsf",[]],
["Linkedin", "Linkedin","https://www.linkedin.com/in/thangdnsf",[]]
]

paginate: 5
paginate_path: "page:num"
timezone: Asia/Bangkok

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
