markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: thangdnsf
author: "Thangdn"
email: thangdn.tlu@gmail.com
name: "Thangdn"
url: http://thangdn.com
domain: thangdn.com
all_categories: [
["Courses", "Courses","/posts/Courses.html"], 
["Blog", "Blog","/posts/blog.html"],
["Mathematic", "Mathematic","/posts/Mathematic.html"],
["Project", "Project","/posts/Project.html"], 
["other", "Other","/posts/other.html"],
["about", "About","/about.html"]
]

paginate: 5
paginate_path: "page:num"
timezone: Asia/Bangkok

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
